### ISSUE TITLE
Constructor shouldn't have any return statement 

### ISSUE THREAD

**Issue by Rishija** [LucasIME/CTCI-Solutions#1]
https://github.com/LucasIME/CTCI-Solutions/blob/0d982ab4018e8a87547d4e79d556294d4261ec12/Chapter12%20-%20C%20and%20C%2B%2B/Q9-SmartPointer.cpp#L37

**Comment by LucasIME** [comment]
Thanks for pointing it out! 

Would you mind sharing how you came across the repo?

**Comment by Rishija** [comment]
a google search for "CTCI solutions"
